name: Check for feat
on:
  push:
    branches:
      - main
jobs:
  check-for-feat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for feat
      run: |
        if [[ $(git log --pretty=format:%s -1) == *"test-ci"* ]]; then
          echo "test-ci found"
        else
          echo "test-ci not found"
        fi
